### ISSUE TITLE
Do we actually need an installer?

### ISSUE THREAD

**Issue by tobychui** [tobychui/arozos#1]
Is there any guideline / reference for an ArOZ Online System installer? 
Is that really pessary in the first place (As currently, we already have a bash script that do the installation) ?

**Comment by yeungalan** [comment]
If we had a installer or something, that will help people to install the system without too many effort.
Just like installing DSM or Wordpress, they don't need to type much command to install it

**Comment by zxj2019** [comment]
I look you have an Synology Server，you know，the intstaller is very easy for our to install DSM system.I think Aroz is the best project on raspberrypi！But also，install is to difficult for our new use linux user，If you can make a **Windows installer** for our windows users，more people will use Aroz system。emm，my English is not good at all，I am hear from your reply，thanks!（I am a AMD64 user，hope Aroz work well in the AMD64-linux,such as centos)

**Comment by yeungalan** [comment]
Hi, thanks for your comment!
The system works in Linux environments (we had tested it on Debian x64 also raspbian). We may add the full support on CentOS but we don't have any plan on that for now.
For the windows host, I believe you could just compile the arozos and it should run fine in Windows.

**Comment by tobychui** [comment]
I wonder what do @zxj2019 means by "Windows Installer". Do you mean "Windows Executable"?
I actually have two idea on this issue
1. Creating a website that can generate a start.bat / start.sh file for starting up the binary depending on your platform
2. Moving all start options into the system / allow in-system-overwrite of start parameters

Which one would you see to best fit the general users?

**Comment by zxj2019** [comment]
> Hi, thanks for your comment!
> The system works in Linux environments (we had tested it on Debian x64 also raspbian). We may add the full support on CentOS but we don't have any plan on that for now.
> For the windows host, I believe you could just compile the arozos and it should run fine in Windows.
> 
> P.S. If you are not comfortable with English, I'm OK with Chinese too :)



> I wonder what do @zxj2019 means by "Windows Installer". Do you mean "Windows Executable"?
> I actually have two idea on this issue
> 
> 1. Creating a website that can generate a start.bat / start.sh file for starting up the binary depending on your platform
> 2. Moving all start options into the system / allow in-system-overwrite of start parameters
> 
> Which one would you see to best fit the general users?

Yes，Thanks for reply! I forget to tell you what's the "windows installer"，I think the best tool is like "UNRAID usb creator"(It's a Executable )，it's a software for flash the system in USB drives. For general users they didn't know how to use linux at all，Aroz can have a ".img"(full system)and use ".bat"to make boot SD card(use windows to flash is easy for new users). Also，have ".sh"for some advanced users in raspbian(such as Auto expert the drives in first，and start run ArozOS) But make a system is to difficult and if the basic system update we can't update to newest at the first time,some safe problems will be appear......So now seem linux installer like best way?And it's easy for you to update,because now didn't have lots users(needn't spend lots of time in windows,more program will have more bug:( 
   )

**Comment by zxj2019** [comment]
> Hi, thanks for your comment!
> The system works in Linux environments (we had tested it on Debian x64 also raspbian). We may add the full support on CentOS but we don't have any plan on that for now.
> For the windows host, I believe you could just compile the arozos and it should run fine in Windows.
> 
> P.S. If you are not comfortable with English, I'm OK with Chinese too :)

Thanks!Very useful for me

**Comment by tobychui** [comment]
> 
> 
> > Hi, thanks for your comment!
> > The system works in Linux environments (we had tested it on Debian x64 also raspbian). We may add the full support on CentOS but we don't have any plan on that for now.
> > For the windows host, I believe you could just compile the arozos and it should run fine in Windows.
> > P.S. If you are not comfortable with English, I'm OK with Chinese too :)
> 
> > I wonder what do @zxj2019 means by "Windows Installer". Do you mean "Windows Executable"?
> > I actually have two idea on this issue
> > 
> > 1. Creating a website that can generate a start.bat / start.sh file for starting up the binary depending on your platform
> > 2. Moving all start options into the system / allow in-system-overwrite of start parameters
> > 
> > Which one would you see to best fit the general users?
> 
> Yes，Thanks for reply! I forget to tell you what's the "windows installer"，I think the best tool is like "UNRAID usb creator"(It's a Executable )，it's a software for flash the system in USB drives. For general users they didn't know how to use linux at all，Aroz can have a ".img"(full system)and use ".bat"to make boot SD card(use windows to flash is easy for new users). Also，have ".sh"for some advanced users in raspbian(such as Auto expert the drives in first，and start run ArozOS) But make a system is to difficult and if the basic system update we can't update to newest at the first time,some safe problems will be appear......So now seem linux installer like best way?And it's easy for you to update,because now didn't have lots users(needn't spend lots of time in windows,more program will have more bug:(
> )

I don't think an automated boot SD card maker script will be any helpful because most Raspberry Pi users already know how to burn an image into their SD card using 3rd party tools.  But you did make your point on the update system perspective. I guess we will need a tool for updating the ArozOS system within the system itself (something like Wordpress update?)

**Comment by Secarian** [comment]
To reach the maximum number of users, the best approach is to make an image available for download and guide the user step-by-step through the installation of the recommended flash program and then through the flashing process, ending with a picture tutorial showing how to insert the SD card into the Raspberry Pi. All that's needed are a functioning image and a website with platform recognition and adjusted instructions. The final missing piece is an update script in the setup process that prompts the user to continue without updating or to reliably execute an update to the latest version, or boot into a working image from which the update can be performed.

**Comment by tobychui** [comment]
Installer scripts are already added to the repo for Debian Linux (and distros that fork Debian).
If you are using Windows, just double click the exe file of the launcher and the launcher will download all files required to boot arozos. I guess we can close this issue.
