### ISSUE TITLE
[BUG] unable to start the service

### ISSUE THREAD

**Issue by morsDeiGH** [tobychui/arozos#100]
After installing arozos on raspberry pi 4, the web client does not work, the command "sudo systemctl status arozos" gives "(code=exited, status=1/FAILURE)". How to fix?
![11](https://user-images.githubusercontent.com/354455/183970965-2acf9311-699a-4bc8-afa7-d58dfaaf5b4c.png)

**Host Information(please complete the following information):**
 - Go version 1.17.6
 - Arozos version 1.124

**Comment by yeungalan** [comment]
Hi, may you please show the log to us?

**Comment by tobychui** [comment]
Hi @morsDeiGH, any updates?
If you don't share us the log, there is nothing we can do.

**Comment by arqueiro** [comment]
I have the same problem, how to fix? where can i find the log files to send it to you?

**Comment by tobychui** [comment]
@arqueiro Check your systemd log `sudo journalctl -u (service_name)`

**Comment by arqueiro** [comment]
```
systemctl status arozos
* arozos.service - ArozOS Cloud Service
     Loaded: loaded (/etc/systemd/system/arozos.service; enabled; preset: enabled)
     Active: inactive (dead)
        Job: 100
```
`journalctl -u arozos
Dec 17 18:05:35 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:05:45 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:05:45 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:05:55 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 1.
Dec 17 18:07:56 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:08:06 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:08:06 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:08:16 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 2.
Dec 17 18:10:16 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:10:26 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:10:26 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:10:36 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 3.
Dec 17 18:12:37 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:12:47 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:12:47 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:12:57 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 4.
Dec 17 18:14:57 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:15:07 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:15:07 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:15:17 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 5.
Dec 17 18:17:18 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:17:28 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:17:28 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:17:38 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 6.
Dec 17 18:19:38 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:19:48 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:19:48 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:19:58 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 7.
Dec 17 18:21:59 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:22:09 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:22:09 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:22:19 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 8.
Dec 17 18:24:19 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:24:29 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:24:29 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:24:39 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 9.
Dec 17 18:26:40 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:26:50 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:26:50 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:27:00 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 10.
Dec 17 18:29:00 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:29:10 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:29:10 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:29:20 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 11.
Dec 17 18:31:21 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:31:31 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:31:31 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:31:41 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 12.
Dec 17 18:33:41 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:33:51 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:33:51 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:34:01 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 13.
Dec 17 18:36:02 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:36:12 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:36:12 aroz systemd[1]: arozos.service: Deactivated successfully.
Dec 17 18:36:22 aroz systemd[1]: arozos.service: Scheduled restart job, restart counter is at 14.
Dec 17 18:38:22 aroz systemd[1]: Starting arozos.service - ArozOS Cloud Service...
Dec 17 18:38:32 aroz systemd[1]: Started arozos.service - ArozOS Cloud Service.
Dec 17 18:38:32 aroz systemd[1]: arozos.service: Deactivated successfully.`

**Comment by tobychui** [comment]
@arqueiro Your Arozos binary cant start for unknown reason (no log even in systemctl). Try uninstall and install it again. Sometime if you are running it on Raspberry pi or something that use SD card, if the binary get corrupted, the binary cant start. 

If that still cant fix the issue, get a new OS.
