### ISSUE TITLE
[Optimization] No advanced sharing options in the pop-up window on desktop.

### ISSUE THREAD

**Issue by konykwong** [tobychui/arozos#104]
## Optimization Needed
No advanced sharing options in the pop-up window on desktop, but the advanced sharing options shown up in the file manager.

## Screenshots
No advanced sharing options in the pop-up window on desktop
![image](https://user-images.githubusercontent.com/69898202/192836082-9d3df39f-0f99-4c55-8d80-3cddfece2c26.png)

The advanced sharing options shown up when opened in the file manager
![image](https://user-images.githubusercontent.com/69898202/192836568-5d0a820a-7d84-4013-8ae1-5c320dc90507.png)

**Comment by tobychui** [comment]
![圖片](https://github.com/tobychui/arozos/assets/24617523/e2f45eec-7744-426c-a2ba-c86b7bec0f75)
Added in v2.108
