### ISSUE TITLE
[BUG] OS Inception

### ISSUE THREAD

**Issue by markusbkk** [tobychui/arozos#106]
**Describe the bug**
I found a way to spawn ArozOS inside itself.

**To Reproduce**
1. Open **MDEditor**
2. Type the URL to a website but without http(s), so the parser treats it as a relative link. I e `[google](google.com)`
3. Toggle Preview (eye symbol)
4. Click on generated link
5. Inside the 404 view, click `Back`
6. The ArOZ Desktop is being loaded inside the MDEditor window

**Expected behavior**
The expected behavior would be to return to the MDEditor view.

**Screenshots**

<img width="959" alt="localhost_desktop system" src="https://user-images.githubusercontent.com/113343009/196693121-10c42fd6-95b8-4e48-bdae-6b3673347492.png">

**Host Information(please complete the following information):**
 - OS: Windows 11 (Tested with both native and WSL2 browsers)
 - Go version: go1.19.1 linux/amd64
 - Arozos version: ArozOS development Revision 0.1.124 (Built from fresh `master` I cloned today, October 19, 2022)

**Client Information(please complete the following information):**
 - OS: Windows 11 64 Bit
 - Browser: Chrome 106.0.5249.119 and Firefox Nightly 107.0a1

**Comment by tobychui** [comment]
Fixed in v2.016 internal preview. Will be closing this issue after 2.0 release.
