### ISSUE TITLE
这个是什么字体，谢谢急需! / What font is this? Thank you for your urgent need

### ISSUE THREAD

**Issue by chenjj100419** [tobychui/arozos#109]
![image](https://user-images.githubusercontent.com/61618153/205482034-31801358-7afd-406b-9fda-964d900798e0.png)
这个是什么字体，谢谢急需! / What font is this? Thank you for your urgent need

**Comment by tobychui** [comment]
4114 Blaster
https://www.dafont.com/4114-blaster.font

Hope it helps :)
