### ISSUE TITLE
Webpage stuck when clicked on "Stationary Remote Clusters" pages

### ISSUE THREAD

**Issue by yeungalan** [tobychui/arozos#11]
![image](https://user-images.githubusercontent.com/12872405/77139732-6004ea80-6a34-11ea-899f-8583a53837c2.png)

**Comment by tobychui** [comment]
![2020-03-20_13-54-28](https://user-images.githubusercontent.com/24617523/77139788-56ba6300-6ab2-11ea-8282-05426a42a33e.png)

Cannot reproduce the issue on Windows 7 + Firefox. Please states your system info.
