### ISSUE TITLE
[BUG] Wrong behavior of drop file on desktop

### ISSUE THREAD

**Issue by KohakuBlueleaf** [tobychui/arozos#110]
**Describe the bug**

**To Reproduce**
1. open dev tool
2. login to an admin account
3. console will output something like "[Desktop] Setting upload mode to large memory mode" and lowMemoryMode is false
4. drag file to desktop
5. it will upload through post since the lowMemoryMode is false. (Nor occured by fallback)

**Expected behavior**
Upload through WS instead of post as default behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/59680068/212719956-3e00895b-76fc-4873-b167-62b306f0a1bd.png)

**Host Information(please complete the following information):**
 - OS: Ubuntu 22.04
 - Go version 1.16.7
 - Arozos version 2.011dev

**Client Information(please complete the following information):**
 - OS: Windows11
 - Browser: Edge
 - Version 109.0.1518.52 

**Additional context**
None

**Comment by tobychui** [comment]
Fixed in v2.010 nightly
