### ISSUE TITLE
[Feature Request] mkdocs Integration for Project Documentation

### ISSUE THREAD

**Issue by Secarian** [tobychui/arozos#119]
**Is your feature request related to a problem? Please describe.**
The current method of documenting the project is time-consuming and difficult to maintain. This affects the ease of translating the documentation into different languages and hosting it on Github.

**Describe the solution you'd like**
We would like to integrate mkdocs into the project to simplify the process of documenting the project. This would allow us to manage the project documentation more easily, with improved translation support and Github integration.

**Describe alternatives you've considered**
We have considered using other documentation tools such as Sphinx and ReadTheDocs, but mkdocs seems to be the best fit for our needs, with its simplicity and ease of use.

**Additional context**
This integration would greatly benefit our team by streamlining the documentation process and improving the accessibility of the documentation for our users. The improved Github integration would also allow for easier collaboration and sharing of the documentation with other stakeholders.

**Comment by tobychui** [comment]
Hi @Secarian ,

You mentioned you are trying to "benefit our team by streamlining the documentation process", are your team trying to work on the documentation of ArozOS?

**Comment by Secarian** [comment]
> Hi @Secarian ,
> 
> You mentioned you are trying to "benefit our team by streamlining the documentation process", are your team trying to work on the documentation of ArozOS?

Yes i want to Translate the Documentation and Website in Standart German and understand the Architecure while doing it. Maybe even make some YouTube Videos explaining stuff.

**Comment by tobychui** [comment]
The official document is now added over [here](https://github.com/aroz-online/ArozOS-Developers)
If you have further request on what should be covered in the documentation, please create an issue over the above repo instead. 

Thanks for your suggestion 👍🏻
