### ISSUE TITLE
[BUG]Invalid Interface Module

### ISSUE THREAD

**Issue by truman1998** [tobychui/arozos#125]
You are seeing this message because the administrator of this system has removed all your interfacing modules. Please contact technical support and show them this page.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/68187484/224480278-1887198a-e06c-4112-9bb2-d805e2bb6eac.png">

**Comment by truman1998** [comment]
Attempt to delete ao.db solved

**Comment by tobychui** [comment]
@truman1998 Cool! You are one of the few people who have the chance to see this error page.
Might I know what you have done that (might have) caused this system error?
