### ISSUE TITLE
[Optimization] Installer - sudo missing

### ISSUE THREAD

**Issue by radim-ek** [tobychui/arozos#130]
Installer use "sudo" in Linux. But sometimes there is not "sudo"  and user is under root.
And therefore not created systemd service.
And ./start.sh" not worked too.

--------"SCREENSHOT" of comand line  BELOW ---------

Do you want to install ArozOS to systemd service? (y/n)y
install.sh: line 133: sudo: command not found
install.sh: line 134: sudo: command not found
install.sh: line 154: sudo: command not found
install.sh: line 157: sudo: command not found
install.sh: line 158: sudo: command not found
install.sh: line 159: sudo: command not found
ArozOS installation completed!

---------------

**Comment by tobychui** [comment]
Hi @radim-ek , thanks for the feedback. I am not too familiar with bash scripting. I am thinking if there are any better ways to do it other than including apt-get install sudo into the installer script. 
You got any recommended way for me to improve it?

**Comment by Morethanevil** [comment]
Those lines are for the systemd service. You can create this yourself easily. Run the installscript and ignore the warnings. Now run create a new service file as root:

`nano /etc/systemd/system/arozos.service`

Put in these lines to run arozos:

```
[Unit]
Description=ArozOS Cloud Service
After=systemd-networkd-wait-online.service
Wants=systemd-networkd-wait-online.service

[Service]
Type=simple
ExecStartPre=/bin/sleep 10
WorkingDirectory=/home/${CURRENT_USER}/arozos/
ExecStart=/bin/bash /home/${CURRENT_USER}/arozos/start.sh

Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Now (still as root) start Arozos with:

systemctl enable --now arozos.service

You can check the status with:

systemctl status arozos.service

**Comment by neonspectra** [comment]
@tobychui A drop-in replacement for using sudo (if you really need root) is:

`su - root -c "yourcommand"`

Explanation:
- `su` - switch user, the most absolutely basic way to be a different user on a Unix based OS
- `-` - Start a login shell
- `root` - The user we want to run our thing as
- `-c` - Flag to run a command under the specific user in the login shell we opened

**Comment by tobychui** [comment]
@neonspectra Thanks for the tips.
In fact ArozOS can work without root, but if that is the case, it pretty much just serve as a web desktop interface like other front-end only projects. To run arozos without root, just download the web.tar.gz and the executable into any folder and run it with ```./arozos```.

Root access is required for disk management (SMART / disk mounting), WiFi utilities and more to make ArozOS useful so to say. Though, making the installer `sudo` optional is not a high priority task so I just leave this here for now. As usual, PRs are welcomed!

**Comment by tobychui** [comment]
Closing issue as the fixes has been merged
