### ISSUE TITLE
[BUG] illegal operation

### ISSUE THREAD

**Issue by dayve218** [tobychui/arozos#133]
after installation, web page for continuing installation doesn't load. running start.sh gives me an illegal operation.

**Comment by tobychui** [comment]
Some older Raspberry Pi models CPU might encounter this issue. A few reports have been received from Chinese users where they get their second hand Raspberry Pi online. 

In such case, you can build from source with the following steps
1. Download and install Golang for armv6l [go1.20.5.linux-armv6l.tar.gz](https://go.dev/dl/go1.20.5.linux-armv6l.tar.gz)
2. Git clone arozos repo
3. cd into /arozos/src/
4. go mod tidy
5. go build

Afterward, your arozos binary should have no issue executing.

**Comment by tobychui** [comment]
Closing this issue as the problem is resolved by build from source
