### ISSUE TITLE
[BUG] error 404 Page not found....

### ISSUE THREAD

**Issue by intraxit** [tobychui/arozos#134]
Hi,

After install on raspberry pi 3b+ I try to get to the web interface on port 8080 to enter a new user.

The user interface briefly shows and than switches to black screen with error 404 Page not found.

I cannot create a new user.

I'm using firefox latest version on tumbleweed linux.

Thank you for your great work and I hope this glitch is fixed quickly!

Cheers

**Comment by intraxit** [comment]
The page tries to load user.system, but I don't see user.system in the web directory !

**Comment by tobychui** [comment]
Hi @intraxit 
I can confirm web.tar.gz contains user.system
![圖片](https://github.com/tobychui/arozos/assets/24617523/c326258a-cfc2-4ae9-baf9-5a758d861a45)

I guess there might be issue with your disk / file system or maybe your disk is running out of space during unzip? Another possibility is that there might be issues regarding the download process where an incomplete zip file is downloaded and unzipped. Can you try manually unzip the web.tar.gz to the same directory as your arozos binary? (Usually located at ~/arozos/)

Thanks for the bug report!

**Comment by intraxit** [comment]
I reextracted web.tar.gz using sudo and everything is working now!

I guess during the installation (I installed twice) the tar extraction did not work correctly as it didn't ran sudo....

Thank you again for the work you did on the nas project and the arozOS, it is really awesome !

**Comment by tobychui** [comment]
@intraxit Glad to know the problem is fixed! 
We currently only tested the arozos web desktop on major OS + browser which does not include FF + tumbleweed linux. Feel free to tinker around in the JavaScript console / inspector and see if you can figure out something. If you do, please open a new issue / PR for the context menu issue. Thanks for your support :)
