### ISSUE TITLE
The flag at language selector was distorted at safari

### ISSUE THREAD

**Issue by yeungalan** [tobychui/arozos#14]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/12872405/77236957-b0895e80-6b80-11ea-870e-32f5c9792b24.png">
As title

**Comment by tobychui** [comment]
The css used in parsing the flags are "ts mini middle aligned image extraRightPadding" which is Tocas UI's issue. Plus, I have no Mac devices for debugging. Please fix it yourself and updates to this issue if solutions are found.

**Comment by yeungalan** [comment]
![image](https://user-images.githubusercontent.com/12872405/77266573-0df2dd80-6c5d-11ea-9ff9-69a28c0f2979.png)
SOLN: @tobychui

**Comment by tobychui** [comment]
![2020-03-23_12-07-32](https://user-images.githubusercontent.com/24617523/77280350-fec46c00-6cfe-11ea-91ed-776df68558b5.png)
However, by removing the display flex, the text no longer inline with the flags. Alternative solution is needed to solve this issue. Can you try to limit the height of each flags for let say 75px? (aka style="height:75px")

**Comment by yeungalan** [comment]
No, the height setting doesn't work, 
Also your fixes will cause more problem. 
For example Flag of Switzerland was square instead of rectangle, so if we apply this fixes it will distort Switzerland flag

**Comment by tobychui** [comment]
Ok then, maybe you can try adding JavaScript to do conditional css editing. However, index is pending to be rewritten soon and I guess we can leave that until index rewrite project.

**Comment by tobychui** [comment]
Grid interface has been deprecated in arozos 1.0. So this issue no longer exists.
