### ISSUE TITLE
[BUG] WebDav causes system crash when uploading pictures(memory overflow)

### ISSUE THREAD

**Issue by Lynnette177** [tobychui/arozos#151]
When upload/download multiple pictures, the system will crash
For me when Im trying to upload about 400 pics, but only 30, then system stop responding.
Im using webdav.This would happen both using raidrive on windows or use ipad
Besides when doing this,
![image](https://github.com/tobychui/arozos/assets/68948483/29040d06-e46d-403a-b5db-a037c841c07a)

**Comment by Lynnette177** [comment]
This is like a memory overflow issue, because even if the transfer is stopped at this time, the memory usage continues to grow continuously

**Comment by tobychui** [comment]
Cannot reproduce issue

![圖片](https://github.com/tobychui/arozos/assets/24617523/acef20e3-e8e1-4b96-97b0-b112e533031e)

I have tested upload 34 mp3 files of total 162MB to my server via WebDAV (Windows 10 + TLS domain), before upload memory use is around 18.3 MB, during upload it peak at around 29MB and after a few minutes GC kicks in and the memory usage back to 18.8MB. 

You sure it is an issue with ArozOS or it is due to other services using up your memory / listening to file changes which caused memory usage spike? Is your writing destination local disk or if your disk too slow?

**Comment by Lynnette177** [comment]
> Cannot reproduce issue
> 
> ![圖片](https://private-user-images.githubusercontent.com/24617523/305685078-acef20e3-e8e1-4b96-97b0-b112e533031e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzE0MzIsIm5iZiI6MTcwODIzMTEzMiwicGF0aCI6Ii8yNDYxNzUyMy8zMDU2ODUwNzgtYWNlZjIwZTMtZThlMS00Yjk2LTk3YjAtYjExMmU1MzMwMzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA0Mzg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YWMwMmYyNDIzODQ4ZGUxZjMxN2UwOTU3ZmE3YmUyOTAyZGI5YTNlMTc5ZGVjOTZlNDg4ZThlNWFiZWY0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kWlPKP6H3JW7hKoqi57nFT36Zdkn1UKHltGumSs2Cx8)
> 
> I have tested upload 34 mp3 files of total 162MB to my server via WebDAV (Windows 10 + TLS domain), before upload memory use is around 18.3 MB, during upload it peak at around 29MB and after a few minutes GC kicks in and the memory usage back to 18.8MB.
> 
> You sure it is an issue with ArozOS or it is due to other services using up your memory / listening to file changes which caused memory usage spike? Is your writing destination local disk or if your disk too slow?

Okay, I noticed more details this morning.
First directly copy in windows file manager(Im using raidrive) will not result in this issue.
Using WINRAR to unzip the archive file will result memory leak.(While using winzip will not result in this)
Using iOS third party WebDav tool to upload pics will also result in this(Such as ES File Browser, upload from File application)
Most important: Moving items(I tried to cut then overlay the same pictures in different folders) will cause memory leak
So it may be something with file manage, like move or something, im not sure.However use windows default applications will never result the crash issue.Also I noticed when using WPS Pictures to broswer pics, this would also happen.
Sry for my English, here are Chinese ver:
我今天早上注意到了一些细节
一个是直接使用windows文件管理器进行拷贝操作，那么不会有任何问题，我尝试过30GB的文件夹也没错误
如果使用WINRAR解压我的图片zip，那么就会导致崩溃，而使用windows自带的解压缩则不会。同样的，在服务器直接用unzip命令解压缩也不会导致异常。所以猜测与WEBDAV有关
使用ios进行访问的时候，我尝试了第三方软件（ES文件管理器）单个上传没有问题，批量上传约20张左右则开始大量吃内存，传输停止
最重要的一件事：我的图片在服务器存了两份，我尝试剪切一份覆盖另一份，那么就会导致内存泄漏，和上面同样的情况。8G swap全部吃满。systemctl重启arozos则一切恢复正常
很奇怪的一件事，使用windows自带照片查看图片，没有问题，使用wps图片查看，导致内存泄漏崩溃
所以我猜测，可能与文件管理中的某些功能相关，例如频繁的移动或访问
可以排除硬盘的问题，因为这个在我多个硬盘同样会发生，硬盘是新买的，只用了两天。
