### ISSUE TITLE
[BUG]problem when accessing nextcloud(hetzner storage share)  webdav

### ISSUE THREAD

**Issue by sdrrrr** [tobychui/arozos#153]
problem occurred when trying to access(upload/download/copy) a webdav storage pool . 
the task windwos shows says 
Put "https://nx2222.your-storageshare.de/remote.php/dav/files/herman/Palworld_0.1.5.1.zip": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

 the nextcloud webdav  is provided by hetzner storage-share (https://www.hetzner.com/storage/storage-share/)

**Comment by sdrrrr** [comment]
![Screenshot 2024-03-11 123746](https://github.com/tobychui/arozos/assets/154994041/f3a6bbaf-6150-4933-8b77-9ce6d126c196)

**Comment by tobychui** [comment]
@sdrrrr  How big is your file and what is the transfer speed of your network?

**Comment by sdrrrr** [comment]
the problem occurs after about 22MB of files being transfered , my network is about 1g

> @sdrrrr How big is your file and what is the transfer speed of your network?

**Comment by tobychui** [comment]
@sdrrrr I figure out what might be the issue. Can you try remove the setTimeout line from the webdavfs module?

https://github.com/tobychui/arozos/blob/128a803c82dd865634f275d46b05ba8b8b37a82e/src/mod/filesystem/abstractions/webdavfs/webdavfs.go#L38

So the mount function become like this
```go
func NewWebDAVMount(UUID string, Hierarchy string, root string, user string, password string) (*WebDAVFileSystem, error) {
	//Connect to webdav server
	c := gowebdav.NewClient(root, user, password)
	err := c.Connect()
	if err != nil {
		log.Println("[WebDAV FS] Unable to connect to remote: ", err.Error())
		return nil, err
	} else {
		log.Println("[WebDAV FS] Connected to remote: " + root)
	}
	return &WebDAVFileSystem{
		UUID:      UUID,
		Hierarchy: Hierarchy,
		c:         c,
		root:      root,
		user:      user,
	}, nil
}
```

and use go build again to see if the issue is fixed?
