### ISSUE TITLE
[BUG]launcher not working on raspberry pi zero

### ISSUE THREAD

**Issue by Original-clane** [tobychui/arozos#155]
when installing launcher as part of the install script, Arozos fails to start when opening the web page with error "unable to connect". starting arozos manually as described in the read.me also fails.
**To Reproduce**
1. ssh to device
2. cd arozos
3. type sudo ./launcher
4. See error "illegal instruction

**Expected behavior**
webpage to open

**Screenshots**

**Host Information(please complete the following information):**
 - OS: Raspbian bullseye
 - Go version  unknown
 - Arozos version 2.0

**Client Information(please complete the following information):**
 - OS: raspbian bookworm
 - Browser Firefox
 - Version 124.0.1 64 bit

**Additional context**
starting manually with sudo ./arozos works.

**Comment by tobychui** [comment]
Well this is a launcher related issue. You should open this issue on the launcher repo instead. Sadly I cannot transfer the issue to the launcher repo (as that is an organization owned repo), you might need to create a new issue over [here](https://github.com/aroz-online/launcher) instead.
