### ISSUE TITLE
[Optimization]install.sh file needs edits to run on raspberry pi zero

### ISSUE THREAD

**Issue by Original-clane** [tobychui/arozos#156]
In the install file there is a typo in the section:
#Create start.sh with arozos command
 the line:
  echo "${sudo}arozos -port=$arozport -hostname=\"$arozosname\"" >> start.sh
should be:
  echo _"${sudo}./arozos -port=$arozport -hostname=\"$arozosname\""_ >> start.sh

in section:
#Create systemd service file
under [Unit]
_After=network-online.target_ needs to be added above the existing "After=" & "Wants=" lines to prevent the service from starting before the network connection is established.

Without these changes I was not able to access the webpage and had an "unable to connect error"

**Comment by tobychui** [comment]
Hi @Original-clane ,

Thanks for the issues!  Can you create a PR and directly add your changes to the installer script? The installer script are mostly contributed by users as there are so many different systems (hardware & OS combinations) out there, it is hard for me to validate / reproduce the error in the installer script. Generally speaking, I will just merge what our users proposed changes for the installer script.

**Comment by Original-clane** [comment]
After further testing i updated original comment to remove a change that is not required. i will look at creating a PR.

**Comment by pi-dal** [comment]
Given that the issue mentioned in this issue has not been applied for PR after two weeks, I have created a PR(#158) for this change.

**Comment by tobychui** [comment]
Fixed by @pi-dal , I am closing this issue.
