### ISSUE TITLE
[BUG]在文件管理中排列文件顺序

### ISSUE THREAD

**Issue by lpfxh** [tobychui/arozos#167]
我的视频文件名称是1.2.3.4.5.以此类推，在选择自然数排序时，顺序是4.1.2.3.5.6.。。14.10.11.是4序列在第一个文件上

**Comment by tobychui** [comment]
@lpfxh 
![圖片](https://github.com/user-attachments/assets/09b35dd9-aed6-47f9-b5c6-8c40a203bfd9)
我這邊沒問題，你是不是在用全型數字，你把檔名改一改再試試看。

**Comment by lpfxh** [comment]
我用了文件名顺序，设置了01.02.03...10.11....21..22，可以。谢谢您的回答
