### ISSUE TITLE
video如何更改默认的视频文件夹

### ISSUE THREAD

**Issue by lpfxh** [tobychui/arozos#168]
我在网络机顶盒上安装的armbain系统，部署的aroz。我的机顶盒emmc只有16G，我挂载了一个U盘64G的，现在有个问题video的播放器只能读取video文件夹下的数据，在video文佳夹的数据可以按照顺序播放，在其它文件夹下，只能到对应文件夹单个点击播放，。这个问题有方式解决吗

**Comment by tobychui** [comment]
@lpfxh 在 ArozOS 掛載你的 U 盤後在 U 盤的根目錄建立一個 `Video` 資料夾，裡面再開新資料夾放你的影片（資料夾名字是播放清單顯示名稱），這樣影片才會被歸檔和建立播放清單。

**Comment by lpfxh** [comment]
按照您的方式完美解决，谢谢。
