### ISSUE TITLE
可以实现，将video的视频分享出去吗

### ISSUE THREAD

**Issue by lpfxh** [tobychui/arozos#169]
可以实现想群晖那样，分享出去，直接打开链接就能播放吗。我将系统映射到外网，可以在外网环境下观看视频

**Comment by tobychui** [comment]
![圖片](https://github.com/user-attachments/assets/a2e1d6a5-9567-4da7-8ba6-78c868fbc9dc)

1. 選擇影片檔案 > 點分享

![圖片](https://github.com/user-attachments/assets/6fc27af7-5259-423e-b6b1-84095865242d)

2. 按一下產生的連接

![圖片](https://github.com/user-attachments/assets/cc7e12c8-49a6-4fda-bf35-5918e36348ce)

3. 下載界面可以直接播放，或是用下面產生的 HTML 代碼來嵌入到其他網站

**Comment by lpfxh** [comment]
可以分享剧集吗。将整部剧集分享出去

**Comment by lpfxh** [comment]
可以分享rtsp视频流出去吗

**Comment by lpfxh** [comment]
如何将分享的链接变成域名

**Comment by tobychui** [comment]
> 可以分享剧集吗。将整部剧集分享出去

你可以直接分享整個資料夾，但是資料夾分享沒有預覽功能。

> 可以分享rtsp视频流出去吗

不支援。只能用 HTTP / HTTPS 或是透過 SMB 分享來串流。

> 如何将分享的链接变成域名

使用你的域名來打開 ArozOS 桌面介面再接分享，系統會自動切換到用域名分享。

**Comment by lpfxh** [comment]
您好，我发现不能提供远程ip访问。我在局域网内提供域名可以，切换成手机网络不可以，是不是限制了连接IP

**Comment by tobychui** [comment]
@lpfxh 這個你要問你的網絡供應商，這不是 ArozOS 的問題。
