### ISSUE TITLE
web下载如何使用

### ISSUE THREAD

**Issue by lpfxh** [tobychui/arozos#170]
web下载软件。不知道如何使用我将https的下载连接添加进去提示报错

**Comment by tobychui** [comment]
web 下載是用伺服器端下載的，下載要求送出去的時候並不會包含如 cookie 之類的 HTTP header，所以沒辦法下載需要登錄 / basic auth 或是封鎖了 bot 的網頁資源。

**Comment by lpfxh** [comment]
[
![01](https://github.com/user-attachments/assets/a54992bd-f3ba-47cb-aae4-83729b01b177)
![02](https://github.com/user-attachments/assets/f4b2e432-9eaa-400a-bc98-1d0279627656)
](url)

**Comment by lpfxh** [comment]
还有浏览器无法进行访问。局域网内路由器的管理地址都无法访问

**Comment by lpfxh** [comment]
您好，您能帮我i提供一个可以下载的连接吗

**Comment by tobychui** [comment]
@lpfxh 大陸的網絡環境我也不懂，你去 tg 群裡找另一位國內的大佬求助會比較好。

**Comment by lpfxh** [comment]
收到

**Comment by lpfxh** [comment]
感谢
