### ISSUE TITLE
SMB远程访问

### ISSUE THREAD

**Issue by lpfxh** [tobychui/arozos#171]
arozos开启了smb，局域网内可以挂载到电脑，可以远程挂载吗。通过广域网。需要路由器开启端口映射什么端口号

**Comment by tobychui** [comment]
@lpfxh 國外可以用 port forward 445，大陸情況不清楚。另外有關在大陸網絡下使用的問題請直接到 [Telegram ](https://t.me/ArOZBeta) 群組裡找中國大陸的 ArozOS 使用者查詢。
