### ISSUE TITLE
[BUG]Thumbnails hot showing from SMB Windows Share

### ISSUE THREAD

**Issue by pierrehunt** [tobychui/arozos#172]
![Uploading Screenshot_2.png…]()
**Describe the bug**
Successfully mounted SMB share but all JPG and PNG files show as icons

**To Reproduce**
Mounted share

**Expected behavior**
I want to see thumbnails pretty please

**Screenshots**

**Host Information(please complete the following information):**
 - OS: Debian Bullseye
 - Latest version

**Comment by pierrehunt** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/e28ec16a-9003-4663-9387-99c755229833)

**Comment by tobychui** [comment]
@pierrehunt The thumbnail function on network file system require read access to the folder as it will store the thumbnail image files under `.metadata/` folder. 

You should double-check if the ArozOS instance you are running have the correct permission to write to the folder you are browsing.

**Comment by pierrehunt** [comment]
Thank you that was a simple fix - super thanks
![Screenshot_3](https://github.com/user-attachments/assets/15fae6f3-b6ce-4780-99e4-bd5dedfdb3cc)
