### ISSUE TITLE
[BUG] agi call readDBItem既時候會出現illegal pointer

### ISSUE THREAD

**Issue by yeungalan** [tobychui/arozos#21]
**Describe the bug**
如果DB 未建立既話call readDBItem會直接出segmentation violation

**To Reproduce**
用agi readDBItem 去read一個唔存在既db
e.g. var folder = readDBItem("PhotoSlideShow", "folder");

**Expected behavior**
return false

**Screenshots**
![image](https://user-images.githubusercontent.com/12872405/96940532-d105f800-1484-11eb-88c9-af5ff4469309.png)

**Host Information(please complete the following information):**
 - OS: macOS 10.15.7
 - Arozos version dev 1.0.103

**Client Information(please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by tobychui** [comment]
Fixed in AGI definition v1.2. Pending to release with arozos 1.104. 
A new function call in AGI is also added to support db table exists check
```

if (DBTableExists("auth")){
    sendJSONResp("true");
}else{
    sendJSONResp("false");
}
```
See UnitTest/backend/dbExists.js and dbNotExists.js for more examples.
Please use this function if you need extra confirmation before db read write.
