### ISSUE TITLE
[Feature request] Shareable link to files

### ISSUE THREAD

**Issue by jivank** [tobychui/arozos#28]
**Describe the solution you'd like**
When right clicking a file, an option to share the file will be available. It will create a link that goes to a landing page which allows guests to download the file.

**Comment by tobychui** [comment]
This was on our to-do list a few months ago and we are working on that right now, what a coincidence :))

![2020-12-06_13-21-27](https://user-images.githubusercontent.com/24617523/101272309-001ec180-37c6-11eb-9c97-853cb130b931.png)

**Comment by jivank** [comment]
It looks good!

**Comment by tobychui** [comment]
Function added in arozos 1.107 updates (Already included in the current source code)
Binary will be released around next week.

The share interface will looks like this : )
![2020-12-13_12-20-38](https://user-images.githubusercontent.com/24617523/102705240-2a8d7600-42c0-11eb-84cc-910b03137d38.png)

**Comment by jivank** [comment]
I have a pullrequest that I put together very quickly that will allow for custom preview images for any file. Would like to discuss how you envision implementing it.

Also would like to report that the UUIDs still exist after renaming the file (also possibly when deleting a file). Perhaps a simple fix would be to purge non-existent shares on startup.

**Comment by tobychui** [comment]
> 
> 
> I have a pullrequest that I put together very quickly that will allow for custom preview images for any file. Would like to discuss how you envision implementing it.
> 
> Also would like to report that the UUIDs still exist after renaming the file (also possibly when deleting a file). Perhaps a simple fix would be to purge non-existent shares on startup.

I am working on a new ArozOS module that allow internal function to run once each night. I guess I will be adding the purge logic there. Can you share the link to your implementation to me for reference? Thanks!

**Comment by tobychui** [comment]
Invalid share UUID cleaning mechanism has been scheduled to be implement in v1.109 release
