### ISSUE TITLE
[Feature request] HTTP / Torrent Download Manager

### ISSUE THREAD

**Issue by jivank** [tobychui/arozos#31]
**Describe the solution you'd like**
A way to manage downloads from a magnet URL, torrent link or HTTP link. Each user would have their own download manager (users don't see another user's downloads).

**Comment by tobychui** [comment]
Sure, I think I will be adding HTTP file download support soon. Thanks for the idea 👍

**Comment by yeungalan** [comment]
Hi, we added the Torrent function!
Please check it out:
https://github.com/aroz-online/TorrentA
