### ISSUE TITLE
Getting Help

### ISSUE THREAD

**Issue by Nivin37** [tobychui/arozos#32]
Not a bug, sorry, unable to find where to ask.

Where do I go for help?

The arozos service will not start and I need documentation or help to move forward.

Thanks.

Steve...

**Comment by yeungalan** [comment]
Could you please provide us with more details regarding the problem? (eg. fatal panic etc..)

**Comment by tobychui** [comment]
Hi! You can find the doc (still work in progress) in the src folder
(arozos/src/diagram and defs/How to add aroz online service.txt )
Could you provide more info on what system you are using? (Raspberry Pi? Other ARM SBC?), do you build it yourself (please provide Go version from ```go version``` or using the pre-build image (version number)?

Also, it will be helpful if you can provide us the results of
```
sudo systemctl status arozos
```

Thanks.

**Comment by tobychui** [comment]
@Nivin37 Any updates on your situation? Or otherwise I will be closing this issue after 30 days of no responses. Thanks!

**Comment by tobychui** [comment]
Closed due to no further debugging information is supplied
