### ISSUE TITLE
[BUG] SYSTEM FOLDER NOT FOUND

### ISSUE THREAD

**Issue by changchichung** [tobychui/arozos#36]
**Describe the bug**
panic: ▒▒ ERROR: SYSTEM FOLDER NOT FOUND ▒▒

**To Reproduce**
download from release and run it .

**Host Information(please complete the following information):**
```
chchang@chchang-Aspire-M3920:~/下載$ cat /etc/os-release 
NAME="Zorin OS"
VERSION="15.3"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 15.3"
VERSION_ID="15"
HOME_URL="https://www.zorinos.com"
SUPPORT_URL="https://www.zorinos.com/help"
BUG_REPORT_URL="https://bugs.launchpad.net/zorin-os"
PRIVACY_POLICY_URL="https://www.zorinos.com/legal/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
**Additional context**

what I do was
```
wget https://github.com/tobychui/arozos/releases/download/dev_v1.107/arozos_linux_amd64
chmod +x arozos_linux_amd64 
./arozos_linux_amd64 
```
then the error comes
```
2020/12/27 20:31:51 ArOZOS(C) 2020 IMUSLAB.INC.
2020/12/27 20:31:51 ArOZOS development Revision 0.1.107
panic: ▒▒ ERROR: SYSTEM FOLDER NOT FOUND ▒▒

goroutine 1 [running]:
main.RunStartup()
	D:/golang/aroz online/startup.go:16 +0x674
main.main()
	D:/golang/aroz online/main.go:106 +0x30e
```

the same error with demo_mode
```
./arozos_linux_amd64  -demo_mode
2020/12/27 20:31:51 ArOZOS(C) 2020 IMUSLAB.INC.
2020/12/27 20:31:51 ArOZOS development Revision 0.1.107
panic: ▒▒ ERROR: SYSTEM FOLDER NOT FOUND ▒▒

goroutine 1 [running]:
main.RunStartup()
	D:/golang/aroz online/startup.go:16 +0x674
main.main()
	D:/golang/aroz online/main.go:106 +0x30e
```

**Comment by tobychui** [comment]
Hi! Thanks for your feedback. 

> To deploy, copy ./web and ./system from the main source code and place it in the same directory as the binary you choose.

According to the release notes, you need to download the web and system folder from the source code and unzip it to the same folder as the binary in order to run it. 

Please try to download the repo as zip and copy the ./src/web and ./src/system to the same directory and try again. Thanks!
