### ISSUE TITLE
[BUG] fierfox 84.0 , can not see applications .

### ISSUE THREAD

**Issue by changchichung** [tobychui/arozos#37]
**Describe the bug**

start menu can not show any applications

**Client Information(please complete the following information):**
 - OS: Zorin Linux ( based on ubuntu 18.04)
 - Browser : Firefox 
 - Version 844.0

**Additional context**
firefox 84.0
https://i.imgur.com/ZReHKri.png

but with chrome/brave browser and microsoft edge it's ok the show applications
https://i.imgur.com/lnVwquD.png

**Comment by tobychui** [comment]
Hi, the screenshot you captured seems to be showing the start menu in "Download" tab in which, on 1.107, should have no webapp with that category. Did your problem also appears in other tabs (like, All / Media tab)? Is there any error message in the JavaScript developer console (Press F12 on Firefox)? Thanks!

**Comment by changchichung** [comment]
Yes .in all tabs.
I will check the error messages

**Comment by tobychui** [comment]
Hi @changchichung , any updates on the error message?
Because I cannot reproduce your error on Firefox 84.0.1 on either Windows 10 and Debian Buster (with GNOME).

**Comment by tobychui** [comment]
I’m closing this issue because it has been inactive for more than a few months. This probably means that it is not reproducible or it has been fixed in a newer version. Thank you for your contribution!
