### ISSUE TITLE
安装登录后无法使用

### ISSUE THREAD

**Issue by llt12213** [tobychui/arozos#43]
[![yV3PYR.png](https://s3.ax1x.com/2021/02/01/yV3PYR.png)](https://imgchr.com/i/yV3PYR)

**Comment by tobychui** [comment]
Can you provide more information on:
你可以提供更多以下的资料吗？

1. Which version of ArozOS you are using
你在使用甚麽版本的 ArozOS 系统
2. Which release you are using (Rpi image or the release binary)
你在使用的是哪个 Release 来源（映像档或是二进制文件）
3. The steps that get you to this error
你看到此错误之前的步骤

In most case, this can be resolved by removing the ao.db file in ./system folder. Try
在大多数情况下，你可以通过删除 ./system 文件夹中的ao.db文件来解决此问题。 试试

```
cd ~/arozos/system/
rm ./ao.db
```

and go through the registration process again to see if the problem have been resolved.
然後再一次试试注册登录，看问题是否已经被解决。

**Comment by llt12213** [comment]
好的，已经解决了，谢谢

**Comment by tobychui** [comment]
Problem resolved by the issue author
