### ISSUE TITLE
[请求]请问下老版本怎么升级啊

### ISSUE THREAD

**Issue by naliujia** [tobychui/arozos#45]
树莓派zero w 用的 
arozos v1.108固件直接刷机 #arozos v1.108 | https://wdfiles.ru/4053d3bfd730aa60
如果要升级到新的版本需要怎么操作呢

试了下载最新源码然后直接执行 
```
git clone https://github.com/tobychui/arozos
cd ./arozos/src/
go build
```
发现版本没有任何变化 求方法  谢谢

**Comment by tobychui** [comment]
If you want to upgrade your system, just replace the binary files, the ./system and the ./web folder with the latest one in src and release and restart your Raspberry Pi.
如果你需要升级你的系统的话，请下载最新版本的 release 二进制文件、并取代原有的 ./system 跟 ./web 资料夹，然後重启 Raspberry Pi 即可。

The current release of 1.109 are still in testing. We will release the binary files by next week. Please wait and update by then.
现在源码的版本虽然是 1.109，但是由於我们还在进行内测，二进制 （release）文件大约还需要一星期左右才会推出，我会建议你下星期才进行升级。

If you insists in building your binary, try build with the following commands
如果你还是想要升级至内测版本，你可以尝试以下指令
```
cd ~/arozos
go build -o ./arozos_linux_armv7
sudo systemctl restart arozos
```

**Comment by naliujia** [comment]
非常感谢你的详细解答，期待你的更新。
辛苦哈哈

**Comment by tobychui** [comment]
I'm closing this issue because it has been inactive for a few months.
