### ISSUE TITLE
User Icon is not shown [BUG]

### ISSUE THREAD

**Issue by fred2088** [tobychui/arozos#47]
![image](https://user-images.githubusercontent.com/8401029/106561581-ed293300-6563-11eb-86cd-0e65f3fb3c3e.png)

**Comment by tobychui** [comment]
Have you tried refreshing the desktop after uploading a new user icon?

**Comment by fred2088** [comment]
no, but should show the default icon :p

**Comment by tobychui** [comment]
> 
> 
> no, but should show the default icon :p

That is already the default icon 🤔🤔🤔

**Comment by fred2088** [comment]
the picture is no picture picture :p and it can't change the icon only without change the password ?!

![image](https://user-images.githubusercontent.com/8401029/107609616-733b2d00-6c7a-11eb-8b52-dc343497fffa.png)

**Comment by fred2088** [comment]
should be like this ?
![image](https://user-images.githubusercontent.com/8401029/107609999-7c78c980-6c7b-11eb-93d7-be26c55b0342.png)
