### ISSUE TITLE
[License] Is this licensed as open-source?

### ISSUE THREAD

**Issue by mikeschinkel** [tobychui/arozos#57]
I learned about ArozOS from [your article on dev.to](https://dev.to/tobychui/i-write-my-own-web-desktop-os-for-3-years-and-this-is-what-it-looks-like-now-2903).  

I came here to see what you did and it is impressive.  So I looked to see how you licensed it and I do not see any known license.  Is it/will you be licensing as open-source using [one of the open-source licenses that GitHub recognizes](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)?

**Comment by tobychui** [comment]
Hi @mikeschinkel , I have provided you a simplified answer on dev.to, and this is a detail answer to your question:  Is this licensed as open-source?

## Is this software's source open and accessible to the public?
Yes, **all** the source code of the ArozOS project has been opened for access on Github. The one I pushed to Github is identical to the one I am using, and your experience of using the system should be identical to mine when you are building the system from source.

For redistribution policy, at the time when I write this reply, you can do whatever you want with the system source code including modify, redistribute of its source and its binary,  as soon as it is used for **personal or educational purposes**. 

## Is this software "open-source software"?
No. This software do not contain a license that fits the definition of the open source initiative requirement of "open-source software" (See [here](https://opensource.org/licenses)). In legal perspective, this software, other than those libraries listed in the System Setting --> Open Source License tab, is Copyrights tobychui (me) and its author (see the contributor list). 

![2021-04-09_16-19-20](https://user-images.githubusercontent.com/24617523/114151199-776c8980-994f-11eb-93b3-66bf27b87006.png)
(You can find the tab in ArozOS System Setting interface as shown above)

Some webapps or subservice (components) used on top of ArozOS are licensed in a way that is satisfy with the definition of "open-source software". Those components are released over at the Open Aroz Online organization in which you can find them [here](https://github.com/aroz-online).

## Licensed version of ArOZ Online System
If you are interested in a version of Aroz that contain a license, you can check out the php written beta version of ArozOS which is licensed under a MIT-like license. You can see the source code of the beta system by switching to the Beta_LTS branch.

## Use ArozOS for commercial projects
There are already a few companies contacted me for using ArozOS as a part of their commercial projects. If you are interested, feel free to find me at imuslab@gmail.com.

**Comment by mikeschinkel** [comment]
Hi @tobychui — Thanks for the detailed clarification.

Good luck with your licensing of it (sincerely.). It is very nice software.

However, as I mentioned over on dev.to we were thinking that if we could package ArozOS as a published Docker container so that Launch could simplify using it it could possible benefit us both.  But since it is not legally open-source it is not a direction we can pursue because of legal liability, sadly.

-Mike

P.S. IMO it is a shame you are choosing to keep it closed source. I think it has the potential to become a defacto-standard browser-based OS for embedded devices if you were to open-source it. 

IMO this is especially true with so many SBCs like Raspberry Pi making it so easy for some many startup entrepreneurs with no fund for licensing software to create embedded devices. Yours could be their go-to browser OS. But as closed-source I doubt it could have a chance of becoming a defacto-standard in an open-source world,sadly. . :-( 

And if you were create an organization around it and it became widely used it would probably be worth a large amount of money in an acquisition, much like how MySQL was acquired by Sun for US$1 billion. But  I think the huge valuations today come from a huge installed base, something that will be all but impossible for close-source, unless you are Microsoft, or...not sure else who could do that.



Anyway, best of luck. And please reach out if you eventually do decide to open-source.

**Comment by tobychui** [comment]
Hi @mikeschinkel , thanks for your detailed explanation and your future visions on this project. I never thought of the dual-license would be a possible option. I will consider this after some research and consulting other contributors in this project.
