### ISSUE TITLE
关于build时出现的错误

### ISSUE THREAD

**Issue by xiaoniu1234** [tobychui/arozos#60]
![image](https://user-images.githubusercontent.com/47274115/117096070-9584a880-ad9a-11eb-93dc-ef6ae7efa4f6.png)
解决了go编译器下载依赖的问题后，又出现了一个新的问题。
编译时，它似乎报错了，在src目录下也并没有出现arozos。
我不太了解go编译器，因此我没有办法自己排查错误，所以这个问题在您眼里可能是个很傻的问题。
但我带着不懂就问的心态，还是新建了一个问题，希望能快速解决。

**Comment by tobychui** [comment]
Hi @xiaoniu1234 

It seems to me that you have been using an outdated Go compiler. To build ArozOS from source, you will need Go compiler 1.14 or above. If you don't know how to install Go 1.14 or above, you can checkout the following tutorial.
https://dev.to/tobychui/install-go-on-raspberry-pi-os-shortest-tutorial-4pb

Feel free to let me know if you still encounter any issue after upgrading your compiler. Thanks!

在我看來你該是使用了一個舊本的 Go 編譯器。就如 README 中寫的，你需要 Go 1.14 或以上的版本才能從源碼建置 ArozOS。如果你不懂如何安裝 Go 1.14 或以上的版本，你可以參閱以下的教學文件（英文）
https://dev.to/tobychui/install-go-on-raspberry-pi-os-shortest-tutorial-4pb

如果你在升級 Go 編譯器之後仍無法建置，請再來找我，謝謝！

**Comment by xiaoniu1234** [comment]
Oh，原来是这样。apt给我安装的golang版本是1.11，是我没认真阅读README。我已经在golang的官网下载了最新的golang并安装，目前，我已经成功构建了arozos并按README中的方法（在超低内存单板计算机上部署、在其启动盘只有不到16GB空间的瘦客户机上进行部署）完美运行了arozos，它现在工作的很好，感谢！

**Comment by tobychui** [comment]
Great to hear that! I am closing this issue now. 
那就好了，那我關 issue 了喔
