### ISSUE TITLE
[BUG] Doesn't works with Raspberry Pi (WiFi internet connection)

### ISSUE THREAD

**Issue by Bellisario** [tobychui/arozos#69]
**Describe the bug**
The system starts and fails at network because I don't have it connected via LAN (but continues equally), so I want to connect it via WiFi. Now, the system continues and arrives to login: I don't know the system login and my user with password, obviously (because it's in another micro SD), doesn't work.
So, my questions are these:
- Is this only available with LAN?
- If no, what is the login user and password?

**To Reproduce**
Just use a Raspberry Pi not connected with LAN: you can see a login where you are not able to login (because you don't know user and password).

**Expected behavior**
Login with default user and password of the Raspberry Pi, or info about login before download.

**Screenshots**
Not applicable.

**Host Information(please complete the following information):**
 - OS: Raspberry Pi 4
 - Go version (if you build it yourself) [e.g. 1.15.0]: Not built myself
 - Arozos version (e.g. 1.100): v1.113

**Client Information(please complete the following information):**
Not needed to explain, the problem is in the server start.

**Additional context**
None.

**Comment by tobychui** [comment]
Hi @Bellisario , I don't understand your question. But I try to give you some information that might help.

1. No. It is not LAN only. In fact, you can set your Pi to connect to your WiFi router using System Settings > Networks > WiFi Settings options
![2021-06-28_22-38-59](https://user-images.githubusercontent.com/24617523/123655693-c8f72700-d861-11eb-8047-8a30aeafeb94.png)

2. What username and password you are looking for? 

For ssh, the username and password are ```pi``` and ```raspberry``` (aka the default password for Raspberry Pi OS). 

If you means the password for the ArozOS system, you should have created an account using the "New User" utilities greeted by your first system launch (which looks like this)
![2021-06-28_22-41-39](https://user-images.githubusercontent.com/24617523/123656000-196e8480-d862-11eb-8394-694fbfeee686.png)
To login, simply use the account information you filled in previously.

If you mean WiFi AP functions, the ArozOS do not have build in WiFi AP support. You have to set it up yourself if you want WiFi AP function on your Raspberry Pi 4.

Please let me know if the above answers can solve your problem with the login issue. Thanks!

**Comment by Bellisario** [comment]
@tobychui, thank you for your help. I successfully logged in and connected to my network!
Unfortunately, there is a problem: I don't find my Raspberry Pi ip (or I found it but the server doesn't works and ping doesn't work) and I can't view it in "Network Neighbourhood", too. All the commands I tested didn't work. Have you any other suggestion? So, it is online (tested with `ping 8.8.8.8`) and using `./start.sh` in arozos folder the server seems to start (but not reachable by other computers in my network or out).

**Comment by tobychui** [comment]
@Bellisario As you are able to start the ArozOS with the given start.sh script and it didn't gives any errors, that means it is not caused by the ArozOS. If it didn't show up in "Network Neighbourhood", you can try to access it directly using ```http://{your_pi_ip_address}:8080/```. 

But seeing from your comment, I guess your problem is more likely to be caused by the network configuration you are using. Some WiFi routers block connections between peers so you will not be able to connect to your Pi using WiFi even both devices are connected to the same WiFi AP. 

You might want to check your router configuration for "Peer-to-Peer(P2P)" settings (or similar, depending on your router's brand). If your problem persists, you should find a friend with IT background to fix the network for you. 

If your problem has been resolve, please let me know and close this issue : )

**Comment by Bellisario** [comment]
Thank you another time for your support @tobychui!
Today I resolved connecting to another router and using `http://{your_pi_ip_address}:8080/`.
I'll close the issue!

P.S.: for who have problems to find the ip address, don't use `ip addr` command, instead use `ifconfig wlan0` (if configured in WiFi) command and take inet ip.
