### ISSUE TITLE
[BUG] Cannot Right Click on Aroz Desktop using Chrome on MacOS Catalina

### ISSUE THREAD

**Issue by konykwong** [tobychui/arozos#74]
**Describe the bug**
Cannot right click on desktop using Chrome on MacOS Catalina

**To Reproduce**
1. Use Chrome on a Mac with Catalina OS 
2. Click on Aroz desktop
3. Right click

**Expected behavior**
No pop-up window will show up.

**Host Information(please complete the following information):**
 - OS: Debian
 - Go version 1.14

**Client Information(please complete the following information):**
 - OS: MacOS Catalina v10.15.7
 - Browser: Chrome
 - Version 92.0.4515.159 (Official Build) (x86_64)

**Comment by tobychui** [comment]
Same issue as #73 regarding the context menu issue on MacOS Chrome,. Will be fixed in #73

**Comment by markusbkk** [comment]
I still got that same issue on Chrome 104.0.5112.110 on ChromeOS.

ArOZ version: 1.124

**Comment by tobychui** [comment]
Hi @markusbkk, could you open a new issue regarding your issue? Also can you provide your browser user-agent information in details? Thanks!

**Comment by markusbkk** [comment]
> Hi @markusbkk, could you open a new issue regarding your issue? Also can you provide your browser user-agent information in details? Thanks!

Sure thing.
#107
