### ISSUE TITLE
[Feature request] System Speed Monitor

### ISSUE THREAD

**Issue by konykwong** [tobychui/arozos#75]
**Is your feature request related to a problem? Please describe.**
We could only see Memory and CPU usage at the moment. May I know if we could improve the system monitor function by monitoring the system speed (upload and download), disk transfer speed, number of users online, etc.? 

Thanks all authors and contributors efforts in making this Aroz OS!

**Comment by tobychui** [comment]
Added in v1.116 by @yeungalan
