### ISSUE TITLE
[Optimization] Share Folder Permission

### ISSUE THREAD

**Issue by konykwong** [tobychui/arozos#76]
## Optimization Needed
- Currently the file/ folder share only support 1) anyone with link, 2) anyone signed in, 3) anyone in the same group.
- If the system has more than 3 groups, may you add 1) a share function with a particular group and 2) a share function with a particular user(s)?

Thanks all authors and contributors in making this OS!

## Screenshots
![image](https://user-images.githubusercontent.com/69898202/130419233-911b3574-d9a7-47cb-8bc4-b75392acf9e6.png)

**Comment by tobychui** [comment]
Feature added in v1.121 nightly, will close this issue after the next release
