### ISSUE TITLE
[Optimization] Hide System Files

### ISSUE THREAD

**Issue by konykwong** [tobychui/arozos#77]
## Optimization Needed
May I know if the system files/ (other files) can be hid? (i.e. having a hide function function like on Ubuntu/Windows)

Thanks all authors and contributors in making this OS!

## Screenshots
![image](https://user-images.githubusercontent.com/69898202/130419622-51a60841-697a-42b6-a16b-a91986d0b00d.png)

**Comment by tobychui** [comment]
Fixed in v1.115 internal preview, will be releasing with ArozOS v1.115
