### ISSUE TITLE
Server Name: ESXI-Ubuntu18

### ISSUE THREAD

**Issue by lw916** [tobychui/arozos#78]
Server Name: ESXI-Ubuntu18
Running on Docker
Only get the size of memory from virtual machine run on Vmware-esxi.
esxi虚拟机除内存外其他配置无法获取。
![image](https://user-images.githubusercontent.com/64794523/133590576-ac22a572-393b-4608-9b13-e420ac68d7c0.png)

_Originally posted by @lw916 in https://github.com/tobychui/arozos/issues/50#issuecomment-920753367_

**Comment by lw916** [comment]
> Server Name: ESXI-Ubuntu18
> Running on Docker
> Only get the size of memory from virtual machine run on Vmware-esxi.
> esxi虚拟机除内存外其他配置无法获取。
> ![image](https://user-images.githubusercontent.com/64794523/133590576-ac22a572-393b-4608-9b13-e420ac68d7c0.png)
> 
> _Originally posted by @lw916 in [#50 (comment)](https://github.com/tobychui/arozos/issues/50#issuecomment-920753367)_

**Comment by tobychui** [comment]
This is not a bug, this is a feature.
