### ISSUE TITLE
[Feature request] Webdav mount function

### ISSUE THREAD

**Issue by pi-dal** [tobychui/arozos#86]
**Describe the solution you'd like**
I want to mount webdav in Arozos. (Such as Alibaba Cloud Disk, Google Drive, Onedrive, etc.)

**Describe alternatives you've considered**
 I hope Arozos can mount webdav of various cloud disks.

**Additional context**
Now Arozos supports webdav sharing, but this is only external. I hope Arozos can realize hybrid cloud disk since mounting webdav.

**Comment by tobychui** [comment]
Hi, thanks for the feature request! 

I guess for the current system architecture for virtual storage devices, it is not possible to implement such feature as a new kind of "network disk". This might need to wait until the cluster subsystem finish before any of this function can be proceeded to the design stage. I will keep this request open for any ideas and discussions.

**Comment by tobychui** [comment]
Added in v2.0
