### ISSUE TITLE
[BUG] Custom User with custom group can't show system info ...

### ISSUE THREAD

**Issue by fred2088** [tobychui/arozos#89]
**Describe the bug**
a new user "test" with a new group "Test" can't display info while admin can show details

**To Reproduce**

**Expected behavior**

**Screenshots**

**Host Information(please complete the following information):**
 - OS: [e.g. Debian Buster]
 - Go version (if you build it yourself) [e.g. 1.15.0]
![image](https://user-images.githubusercontent.com/8401029/162132410-41bee04d-b68f-42ad-a6cb-36e894c74cd1.png)

 - Arozos version (e.g. 1.100)

**Client Information(please complete the following information):**
 - OS: [e.g. Windows 7 SP2]
 - Browser [e.g. Chrome / Firefox]
 - Version [e.g. 81.0.2 (64-bit)]

**Additional context**

**Comment by fred2088** [comment]
Another issue is when group qota is changed from 100KB to 100MB, the user quota limit is still 100KB ?

**Comment by fred2088** [comment]
is it to hide "Disk Space" like other TAB ? instead of showing Permssion Denied when clicking the TAB ?

![image](https://user-images.githubusercontent.com/8401029/162135183-4f07c574-c213-4363-86c2-80f07af10498.png)

**Comment by tobychui** [comment]
It seems you have invalid group permission setting regarding the new user group.
Are you sure you have allowed the new user group to access "System Setting" module?
Can you screenshot the user group permission setting for us? 
Thanks!

**Comment by fred2088** [comment]
all are default settings with only define 100KB first hand and then changed to 100MB
![image](https://user-images.githubusercontent.com/8401029/162189948-c309166a-5170-4f13-9f86-eb7a094b9060.png)

**Comment by tobychui** [comment]
> all are default settings with only define 100KB first hand and then changed to 100MB ![image](https://user-images.githubusercontent.com/8401029/162190250-d904c454-23df-4c89-bd4c-551b63a15d97.png)

It seems you have a wrong  "Allow Access" permission setting. In normal cases where you want to create a permission group for human users, you have to put at least "File Manager", "System Settings" and "Trash Bin" into the allow access module list. A permission group with "Allow Access" permission empty is usually for bots or a customize interface module (e.g. billboard). 

Here is an example setting for a "design for human" user group: 
![圖片](https://user-images.githubusercontent.com/24617523/162199021-4f277f8c-4a2e-4fb8-bbb9-31e15aef8ef0.png)

**Comment by fred2088** [comment]
Ha Ha, only GOD knows ...

**Comment by fred2088** [comment]
> Another issue is when group qota is changed from 100KB to 100MB, the user quota limit is still 100KB ?

How about this ?

**Comment by fred2088** [comment]
> > all are default settings with only define 100KB first hand and then changed to 100MB ![image](https://user-images.githubusercontent.com/8401029/162190250-d904c454-23df-4c89-bd4c-551b63a15d97.png)
> 
> It seems you have a wrong "Allow Access" permission setting. In normal cases where you want to create a permission group for human users, you have to put at least "File Manager", "System Settings" and "Trash Bin" into the allow access module list. A permission group with "Allow Access" permission empty is usually for bots or a customize interface module (e.g. billboard).
> 
> Here is an example setting for a "design for human" user group: ![圖片](https://user-images.githubusercontent.com/24617523/162199021-4f277f8c-4a2e-4fb8-bbb9-31e15aef8ef0.png)

It's a bit incorrect to allow use the "system settings" without permission !

**Comment by tobychui** [comment]
> > Another issue is when group qota is changed from 100KB to 100MB, the user quota limit is still 100KB ?
> 
> How about this ?

This is working by design. When you change the group quota, it only applies to any new users added to the group. It is necessary to implement this way due to the complexity of a multi-user multi-permission group system.

> It's a bit incorrect to allow use the "system settings" without permission !

This is also normal. If a user do not have access to system settings module, the user can only load the template of the system setting but not any function or API call from it (That is why when you try to open it with a user that has no access permission to the system setting / info tab, it shows all undefined and not usable). 

The issue is the invalid configuration of auto created shortcut on desktop where you can customize what to create on user creation by changing the content in the system/desktop/template/ folder.

**Comment by fred2088** [comment]
Totally agree if it's self explained when creating group or have a option as default settings ...
