### ISSUE TITLE
[BUG] Unauthorized file&folder access of other users under certain situations

### ISSUE THREAD

**Issue by gafea** [tobychui/arozos#92]
**Describe the bug**
Any user, whether admin or not, can access other users' files and folders that starts with their username placed in files/users/ without having their passwords, given that they already knows the victim's username.

For example, a user with username 'ga' can access any files of user 'gafea' or 'gajdnfhgioasdhf'

**To Reproduce**

1. Having an admin account, in my case my username will be 'gafea'
2. Create a file on desktop, e.g. a text file called 'secret.txt', type something and save it
3. Create a user with username that starts with my username, e.g. 'ga'. Having admin permission or not is not important
4. Start another browser or go incognito and sign into the new account just created
5. Start new acc's devtools and POST to `[domain]/system/file_system/listDir` with `dir=user:[char diff between victim's username and mine]/`, like `dir=user:fea/` ...
![image](https://user-images.githubusercontent.com/103837965/164245474-9de8c046-be20-488e-b0c7-5bff84b32da7.png)

6. ...which returns a JSON of the 'gafea' user root folder! We are looking at 'gafea''s folders from 'ga' account!
![image](https://user-images.githubusercontent.com/103837965/164245308-244ef6ce-738d-4354-ba59-0c370760d351.png)

7. When we changes to `dir=user:fea/Desktop/`, which returns the files contained in 'gafea''s desktop, we can see that secret.txt is listed too.
![image](https://user-images.githubusercontent.com/103837965/164244521-28979639-8b6e-411c-97b1-ea09fee3d729.png)

8. Using the /media/ api, we can even issue a GET to the secret.txt and read it's content too!
![image](https://user-images.githubusercontent.com/103837965/164246365-ef1b062b-3ba9-432a-b6b1-92d2b2e7a283.png)
![Untitled](https://user-images.githubusercontent.com/103837965/164246963-b122027f-7cbd-4c59-9136-84215f7c7046.png)

Sidenote: I have only tested on Windows which works and haven't tested on arm or linux yet.

**Host Information(please complete the following information):**
 - OS: Windows 11
 - Arozos version v1.120 (latest)

**Client Information(please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox 99.0.1 / Chrome 100.0.4896.127

**Comment by tobychui** [comment]
Thanks for your bug report. This seems to be a really critical bug and I will see if I can fix it within this week. 
My guess would be the virtual path translation logic got something screwed up, I will look into it later tonight.
@yeungalan can you check if you can reproduce this on your nightly build as well?

**Comment by yeungalan** [comment]
Yes I am able to recreate this bug

**Comment by tobychui** [comment]
Patch has been released with v1.121

**Comment by gafea** [comment]
// Big thanks for your imminent response to the issue!
// However rushed patches often causes more problems doesn't it 👀

**Describe the (new) bug**
Any user, whether admin or not, can utilize directory traversal attack to access **all** users' files and folders placed in files/users/ without having their passwords.

**To Reproduce**
Steps to reproduce the behavior:

1. Start any acc's devtool and POST to `[domain]/system/file_system/listDir` with `dir=user:../` will return a list of existing accounts saved on the server
![image](https://user-images.githubusercontent.com/103837965/164896549-85b34eec-8d5d-4335-9bd8-8852ed3874b2.png)
![image](https://user-images.githubusercontent.com/103837965/164896587-3f5a5320-dc78-40e3-92b3-bc7407218f99.png)

2. I am currently signed in with 'ga', POSTing with `dir=user:../fea/Desktop/` returns the folder of user 'fea' without any headaches
![image](https://user-images.githubusercontent.com/103837965/164896748-61a667a3-3ed5-4568-9ed5-7fd03dff290d.png)

3. Accessing files with /media/ API also works
![Untitled](https://user-images.githubusercontent.com/103837965/164896955-bda43218-e6bb-4f70-834f-bba1639dde43.png)

**Host Information(please complete the following information):**

- OS: Windows 11
- Arozos version v1.121

Maybe you can try mitigate the possibility of phasing any string between `user:` and the first slash? Like changing the return value of `user:` from `files/users/gafea`to `files/users/gafea/` and remove the starting slash from apps calling the API. I did see you trying to mitigate directory traversal in the codebase so `user:/../` doesn't work. This is a fantastic project and keep your passion!

**Comment by tobychui** [comment]
Ok, it seems this bug will stick around for a while. Let me re-open this and try to figure out a better solution to fix it. (๑´ㅁ`)

**Comment by tobychui** [comment]
Hi @gafea,
You mind testing with the latest patch to see if it has been resolved? (You might need to build from source as I didn't create a release for this experimental patch). 

From my testing it seems this time all directory traversal is blocked. I am also asking our coauthors to help test things out. Thank you so much for your time and effort to help make arozos a safer system :)

**Comment by gafea** [comment]
That patch looks good to me 👍🏻

**Comment by tobychui** [comment]
> That patch looks good to me 👍🏻
> 
> Edit: It should be reminded that trying to access files with two dots in it's filename is also blocked by this screening 👀 ![image](https://user-images.githubusercontent.com/103837965/164957075-64089d0e-bf85-42de-910b-9a4e0d1c6e3d.png)

Nice to know! Now I am closing this issue and will be releasing the 1.121v3 later.
