### ISSUE TITLE
0.1.122 升級問題

### ISSUE THREAD

**Issue by rai1872** [tobychui/arozos#96]
下載web.tar.gz 後將 web  及 system 覆蓋原來的 web 及 system ，開啟後 顯示的版本 還是 0.1.122
請問是升級方式錯誤嗎

**Comment by yeungalan** [comment]
Hi, 請問你有沒有下載到相應的binary file(二進制檔案)?

**Comment by yeungalan** [comment]
![image](https://user-images.githubusercontent.com/12872405/176840059-bae52a0b-1047-45c5-952e-4feb9cc284d6.png)

**Comment by tobychui** [comment]
Hi @rai1872, is @yeungalan solution solved your issue? If yes, please close this issue.
請問 Alanyeung 的解答是否已解決你的問題？如果是的話請關閉此 Issue。
